name: Deploy Next.js application

on:
  push:
    branches:
      - deploy-with-docker-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
      - name: Build Docker image
        run: docker build -t itslynn/nextjs-app .
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Publish image to DockerHub
        run: docker push itslynn/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from DockerHub
        run: docker pull itslynn/nextjs-app:latest
      - name: Delete old container
        run: docker rm -f nextjs-app-container
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-container itslynn/nextjs-app
